### PR TITLE
TST: convert to unitest framework

### LINKED ISSUE #1: Figure out how to convert tests to unittest framework
I have made an attempt on the `unittest` branch, but so far I cannot figure out how to make the tests runnable due to trouble with the package's relative imports.

### PR DESCRIPTION
**Pull request by marchdf**
Tests can be run by exectuting `nosetests` in the `python-nufft`
directory. Also the test file was moved to a testing directory to
conform with best practices. PEP8 formating was used to format
the resulting files. This fixes #1 .

### CODE REVIEW

**Comment by marchdf** [comment]
I actually redid a lot of the testing (including 2D) and added a Sphinx documentation framework to this. I also added the 3D bindings and am going to implement tests for those as well. This is all on my `develop` branch of my fork. So maybe it makes sense hold off on this pull request... Feel free to let me know what you think.

**Comment by ThomasA** [comment]
I will be happy to include this pull request. I am just a bit buried in trying to work through a huge backlog before the holidays. It could take another week or more.

**Comment by marchdf** [comment]
No problem! I am actually adding some stuff, so maybe it makes sense to close this and I will reopen with the new stuff I am adding.

**Comment by ThomasA** [comment]
You can also add multiple PRs if you want, so I can review separate 
"things" in separate requests.

**Pull request closed without merging**
